src/downloads.html:
  Main_Modpack_Name: All the Mods 9 - ATM9
  Main_Modpack_Link: https://www.curseforge.com/minecraft/modpacks/all-the-mods-9
  Main_Modpack_Launcher_Link:
  Main_ModPack_Traditional_Link:
  Main_ModPack_Curseforge_Link: https://www.curseforge.com/minecraft/modpacks/all-the-mods-9/files/4728062

